PORTNAME										= pgtap
DISTVERSION									= 1.2.0
DISTVERSIONPREFIX						= v
CATEGORIES									= databases
MAINTAINER 									= me@peeyushsingh.com
COMMENT 										= PostgreSQL Unit Testing Suite
LICENSE 										= MIT
WWW													= https://github.com/theory/pgtap

USE_GITHUB 									= yes
GH_ACCOUNT 									= theory
GH_PROJECT 									= ${PORTNAME}
GH_TAGNAME 									= ${DISTVERSIONFULL}

USES 												= gmake pgsql

.sinclude "Makefile.vendored"
.include <bsd.port.mk>
