# Created by: Peeyush Singh <me@peeyushsingh.com>

PORTNAME=									click-repl
PORTVERSION=							0.2.0
CATEGORIES=								devel python
MASTER_SITES=							CHEESESHOP
PKGNAMEPREFIX=						${PYTHON_PKGNAMEPREFIX}

MAINTAINER=								me@peeyushsingh.com
COMMENT=									Python subcommand REPL for click apps

LICENSE=									MIT

RUN_DEPENDS=						  ${PYTHON_PKGNAMEPREFIX}prompt-toolkit>=0:devel/py-prompt-toolkit@${PY_FLAVOR}

USES=											python
USE_PYTHON=								autoplist concurrent distutils allflavors

NO_ARCH=									yes

.include <bsd.port.mk>
