PORTNAME=								wcwidth
PORTVERSION=						0.1.8
CATEGORIES=							devel python
MASTER_SITES=						CHEESESHOP
PKGNAMEPREFIX=					${PYTHON_PKGNAMEPREFIX}

MAINTAINER=							skreuzer@FreeBSD.org
COMMENT=								Determine the printable width of the terminal
LICENSE=								MIT

USES=										python
USE_PYTHON=							autoplist concurrent distutils allflavors
NO_ARCH=								yes

.include <bsd.port.mk>
