PORTNAME=											tea
DISTVERSION=									0.9.0
DISTVERSIONPREFIX=						v
PORTREVISION=									1
CATEGORIES=										devel
MAINTAINER=										me@peeyushsingh.com
COMMENT=											A command line tool to interact with Gitea servers
LICENSE=											MIT
WWW=													https://gitea.com/gitea/tea

USES=													go:modules
GO_MODULE=										code.gitea.io/tea

PLIST_FILES= 									bin/${PORTNAME}

.include <bsd.port.mk>
