PORTNAME=							click-didyoumean
PORTVERSION=					0.3.0
CATEGORIES=						devel python
MASTER_SITES=					CHEESESHOP
PKGNAMEPREFIX=				${PYTHON_PKGNAMEPREFIX}

MAINTAINER=						me@peeyushsingh.com
COMMENT=							Enable git-like did-you-mean feature in click

LICENSE=							BSD3CLAUSE

USES=									python
USE_PYTHON=						autoplist distutils allflavors
NO_ARCH=							yes

.include <bsd.port.mk>
