--- Cargo.toml.orig	2022-07-29 18:15:00 UTC
+++ Cargo.toml
@@ -26,7 +26,7 @@ hkdf = "0.12"
 uuid = { version = "1.1", features = ["v4"] }
 
 serde = { version = "1.0", features = ["derive"] }
-serde_json = "1.0.82"
+serde_json = "1.0"
 tokio = { version = "1.20", features = ["full"] }
 reqwest = { version = "0.11", features = ["json", "gzip"] }
 cursive = { version = "0.19", default_features = false, features = ["crossterm-backend"] }
@@ -34,14 +34,21 @@ cursive_table_view = { git = "https://github.com/luryu
 log = "0.4"
 lazy_static = "1.4"
 clap = { version="3.2", features = ["derive"] }
-directories-next = "2.0.0"
+directories-next = "2.0"
 thiserror = "1.0"
 anyhow = "1.0"
 zeroize = { version = "1.5", features = ["zeroize_derive"] }
 simsearch = "0.2"
 
 [target.'cfg(windows)'.dependencies]
-clipboard-win = { version = "4.4.2", features = ["std"] }
+clipboard-win = { version = "4.4", features = ["std"] }
 
 [target.'cfg(target_os="linux")'.dependencies]
 x11-clipboard = { git = "https://github.com/luryus/x11-clipboard", tag = "v0.6.1+multitarget.1", version = "0.6.1" }
+
+[target.'cfg(target_os="freebsd")'.dependencies]
+x11-clipboard = { git = "https://github.com/luryus/x11-clipboard", tag = "v0.6.1+multitarget.1", version = "0.6.1" }
+
+[profile.release]
+opt-level = 2
+debug = false
