PORTNAME=								zope.event
PORTVERSION=						4.1.0
CATEGORIES=							devel python zope
MASTER_SITES=						CHEESESHOP
PKGNAMEPREFIX=					${PYTHON_PKGNAMEPREFIX}
DIST_SUBDIR=						zope

MAINTAINER=							zope@FreeBSD.org
COMMENT=								Very basic event publishing system

LICENSE=	 							ZPL21
LICENSE_FILE=						${WRKSRC}/LICENSE.txt

USES=										python
USE_PYTHON=							autoplist distutils allflavors
NO_ARCH=								yes

.include <bsd.port.mk>
