PORTNAME= 												ripdrag
PORTVERSION= 											0.1.0
CATEGORIES=												deskutils
MAINTAINER=												me@peeyushsingh.com
COMMENT=													Drag and Drop utility written in Rust and GTK4
LICENSE=													GPLv3
LICENSE_FILE=											${WRKSRC}/LICENSE
WWW=															https://github.com/nik012003/ripdrag

USE_GITHUB= 											yes
GH_ACCOUNT=												nik012003
GH_PROJECT=												${PORTNAME}
GH_TAGNAME=												e5e2bcb7bdc3497ccadc66a7e1a022395e51a732

USES=															cargo
USE_GNOME=												gtk40

PLIST_FILES=											bin/ripdrag

.include <bsd.port.mk>
