PORTNAME=										vine
PORTVERSION=								5.0.0
CATEGORIES=  								devel python
MASTER_SITES= 							CHEESESHOP
PKGNAMEPREFIX=							${PYTHON_PKGNAMEPREFIX}
MAINTAINER=     						olgeni@FreeBSD.org
COMMENT=										Promise library for Python
LICENSE= 										BSD3CLAUSE

USES=												python
USE_PYTHON=									autoplist distutils allflavors
NO_ARCH=										yes

.include <bsd.port.mk>
