# Created by: William Grzybowski <william88@gmail.com>
# Updated by: Peeyush Singh <me@peeyushsingh.com>

PORTNAME=						billiard
PORTVERSION=				4.0.2
CATEGORIES=					devel python
MASTER_SITES=				CHEESESHOP
PKGNAMEPREFIX=			${PYTHON_PKGNAMEPREFIX}

MAINTAINER=					olgeni@FreeBSD.org
COMMENT=						Python multiprocessing fork with improvements and bugfixes

LICENSE=						BSD3CLAUSE

USES=								python
USE_PYTHON=					autoplist distutils allflavors
NO_ARCH=						yes

.include <bsd.port.mk>
